wazo-platform/wazo-confd

integration_tests/suite/base/test_registrars.py
wazo_confd/plugins/registrar/api.yml
wazo_confd/plugins/registrar/model.py
wazo_confd/plugins/registrar/schema.py

The field was missing and was being deleted from the config when updating a registrar. It made it possible to delete a registrar after updating it.

WAZO-993 registrars: add deletable field

---

wazo_confd/plugins/access_feature/api.yml

reason: there was a superfluous required field with a field that does
not exist. The syntax was also wrong. It is weird that the validator has
not seen this mistake.

access_feature: fix swagger

---

integration_tests/suite/base/test_registrars.py

reason: main_host is autogenerated and the test failed once because we
were searching for `2.3` and the main_host of the HiddenRegistrar was
`55.22.37.54`, thus being returned. Fixed by searching for `1.2.3`
instead.

registrars: fix search test

---

wazo_confd/plugins/agent_skill/notifier.py
wazo_confd/plugins/agent_skill/tests/test_notifier.py

reason: asterisk need to reload queueskills.conf

agent_skill: reload app-queue after di/association

---

wazo_confd/plugins/user_import/auth_client.py
wazo_confd/plugins/user_import/tests/test_auth_client.py

if the creation of the auth user associated to a pbx user fails log the error
and keep working on the import.
This change has the following effect.
1. No 500 error because the error is handled
2. No leaked auth user which then cause 409 errors when trying to create users
3. Allow the auth users to be rolledback at the end of the import

user import: handle auth error on user creation

---

wazo_confd/plugins/confbridge/api.yml
wazo_confd/plugins/conference/api.yml

Add links to the sample configuration file for confbridge in the API spec since
the help in the wiki misses some of the fields that are available.

confbridge: add links to the sample config file in the API spec

---

integration_tests/suite/helpers/database.py

reason: duplicate fields from extensions

remove number/context from groupfeatures

---

CHANGELOG.md
integration_tests/suite/base/test_call_pickup_target_group.py
integration_tests/suite/base/test_call_pickup_target_user.py
integration_tests/suite/base/test_users.py
wazo_confd/plugins/user/api.yml
wazo_confd/plugins/user/schema.py
wazo_confd/plugins/user/tests/test_schema.py
wazo_confd/plugins/user_line/tests/test_notifier.py

reason: this is to make it possible to see which users and groups a user
can intercept.
Depends-On: wazo-platform/xivo-dao#14

WAZO-999: add call_pickup_targets in schema

---

integration_tests/suite/base/test_extensions.py

Depends-on: https://github.com/wazo-platform/xivo-dao/pull/26

assert that GET /extensions only trigger one database query

---

CHANGELOG.md
integration_tests/suite/wizard/test_wizard.py
wazo_confd/plugins/wizard/api.yml
wazo_confd/plugins/wizard/resource.py
wazo_confd/plugins/wizard/service.py

GET /wizard now include a boolean indicating if provd is ready to handle HTTP
requests. This is useful because the POST on /wizard will fail if provd is not
started.

wizard: add the provd_ready field to GET /wizard

---

integration_tests/suite/base/test_pagings.py

Why:
* The paging fixture is created with a random number. If this number is
equal to the fixed 666 number of the test, then the test fails.
How:
* Use a fixed number for the fixture also.

integration tests: fix random number colliding with fixed number

---

integration_tests/suite/base/test_incalls.py

reason: for avoid breaking change we do not authorize to have
destination=null. So a fix has been added in xivo-dao to always return
destination={type: none} and we ensure that tests pass here
Depends-on: https://github.com/wazo-platform/xivo-dao/pull/34

test: check incall destination when it's deleted

---

wazo_confd/_sysconfd.py
wazo_confd/plugins/access_feature/notifier.py
wazo_confd/plugins/access_feature/tests/test_notifier.py

It is a temporary solution. xivo-sysconfd should listen on events and
restart service asynchronous ... or better, phoned should listen on
events and reload service according ... or even better, phoned should
handle its own configuration.
Summary: this is one of the worst solution that can be done
EDIT: but the best for the time involved

accessd_feature: restart phoned when update values

---

integration_tests/suite/base/test_pjsip_doc.py
wazo_confd/plugins/pjsip/plugin.py

content is served to the /asterisk/pjsip/doc keeping the type field there and
not accepting it in a PUT on /asterisk/pjsip/global or /asterisk/pjsip/system is
misleading

pjsip doc: remove internal fields from the cached doc

---

integration_tests/suite/base/test_conference_extension.py

we only switch the creation order. Because if conference/extension are
associated, the conference MUST be deleted BEFORE the extension.
Otherwise the extension will raise an error, which doesn't do a failure,
but extension remains and may create conflict with other tests

test: clean conference/extension after associated

---

integration_tests/suite/base/test_registers_sip.py
wazo_confd/plugins/register_sip/resource.py
wazo_confd/plugins/register_sip/validator.py

I did not go all the way with a foreign key to allow transports to be renamed. This code will be removed pretty soon.

register sip: only allow configured transports

---

wazo_confd/plugins/device/model.py

When you have a device with a config that does not exists anymore you GET a 500
when doing a GET on /devices with no indication of the bad device. From that
point you need to have a good understanding of wazo-provd-cli to be able to find
that corrupted device and remove it.

devices: add the device id on the corrupt device error

---

README.md

Small typo in the introduction.

Typo XiVO => Wazo in the readme

---

etc/nginx/locations/https-available/wazo-confd

I don't know if it's the right choice (add regex) or if we should only set the same timeout for all endpoints. The same logic can also be applied to the `client_max_body_size`

nginx: increase timeout for ha endpoint

---

etc/nginx/locations/https-available/wazo-confd

reason: The old configuration didn't keep the query string when
forwarded to wazo-confd. Since this sub location wasn't really useful,
we can remove it

nginx: remove specific location for max_body_size

---

etc/wazo-confd/config.yml
integration_tests/assets/etc/wazo-confd/conf.d/50-default.yml
integration_tests/suite/helpers/provd.py
wazo_confd/config.py

Depends-on: https://github.com/wazo-platform/wazo-provd/pull/28

use provd without ssl by default

---

wazo_confd/plugins/user/notifier.py
wazo_confd/plugins/user/tests/test_notifier.py

Depends-On: https://github.com/wazo-platform/xivo-bus/pull/23

WAZO-1809: add tenant_uuid to forward and service events

---

integration_tests/suite/base/test_event_handlers.py
integration_tests/suite/base/test_sync_db.py
wazo_confd/plugins/event_handlers/service.py

this template only adds registration options and generate warnings in the CLI
when trunks do not have a registration

pjsip: rename global-trunk to trunk-with-registration

---

integration_tests/suite/base/test_registrars.py
wazo_confd/plugins/registrar/dao.py

it was overwritten by a filter that always returned empty list

registrar: fix offset/limit query

---

integration_tests/suite/base/test_user_external_apps.py
wazo_confd/plugins/endpoint_sip/api.yml
wazo_confd/plugins/user_external_app/api.yml
wazo_confd/plugins/user_external_app/resource.py
wazo_confd/plugins/user_external_app/schema.py
wazo_confd/plugins/user_external_app/service.py

About the `Why did you add a view=fallback on listing`:
I think it's a nice feature to have and doesn't require much effort while adding the `get`. Moreover, if limitations are documented properly, then why not.
But I don't have a strong opinion, if someone think it should not be implemented now, I have no objection to remove this part (sorry to not have separated my commits)

Wazo 2043 external app fallback

---

integration_tests/suite/base/test_external_apps.py
wazo_confd/plugins/external_app/resource.py
wazo_confd/plugins/external_app/validator.py

* external_app: allow to use same name across tenant
* external_app: do not cross tenant for endpoints
reason: name is not unique compared to id/uuid and it's not relevant to
return the first item in all tenants you're authorized. We should just
keep the tenant from the header or tenant to search the item and avoid
recurse

Pull request for fix-external-app

---

wazo_confd/helpers/restful.py

Depends-on: https://github.com/wazo-platform/xivo-lib-python/pull/60
reason: when using recurse=True, flask helpers already fetch tenants. So
instead to fetch list twice, we use the same list

use flask helpers to avoid duplicate requests

---

integration_tests/suite/base/test_trunk_endpoint_sip.py
wazo_confd/plugins/trunk/schema.py
wazo_confd/plugins/trunk_endpoint/notifier.py
wazo_confd/plugins/trunk_endpoint/tests/test_notifier.py

the client_uri field is required to match the endpoint to a trunk registration
event.

trunk endpoint sip: add the client_uri to registration section

---

wazo_confd/plugins/endpoint_sip/notifier.py
wazo_confd/plugins/endpoint_sip/tests/test_notifier.py

reason: wazo-calld need it when the endpoint_sip is associated to a
trunk to know its sip_username

send registration_section_options in sip events

---

wazo_confd/plugins/moh/api.yml

reason: this notice was already in the wazo documentation
(wazo-platform.org)

moh: deprecate mp3

---

wazo_confd/plugins/user/api.yml

in 21.03 the AGI has been updated to record the side of the call matching the
user with the recording option. The previous versions always recorded the
calling side of the channel.

recording: remove the recording warning

---

integration_tests/suite/base/test_documentation.py
integration_tests/suite/base/test_func_keys_destinations.py
integration_tests/suite/helpers/base.py
integration_tests/suite/helpers/database.py
integration_tests/suite/helpers/provd.py

reason: service_port() returns only port bound to ipv4. Some host can
resolve localhost to ipv6 address and docker doesn't necessarily bind
the same port number on ipv4 and ipv6

test: use explicit ipv4 addr to connect docker

---

wazo_confd/plugins/agent/api.yml

why: Statistics don't support to change agent number

agent: add documentation about number edition

---

etc/nginx/locations/https-available/wazo-confd
etc/nginx/wazo-confd-shared.conf

Add a file with the rules for wazo-confd that needs to be included in all confd
resources.
create new location paths for no authentication resources.

nginx: add the "base" rules for confd to a separate file

---

etc/nginx/locations/https-available/wazo-confd
etc/nginx/wazo-confd-shared.conf

will prevent the reload from failing if wazo-nginx is not installed

nginx: ignore missing files on reload

---

integration_tests/suite/base/test_event_handlers.py

Why:
* The test fails half of the time for a good reason. Skipping until the
feature is fixed: https://wazo-dev.atlassian.net/browse/WAZO-2752

event handlers: skip test of device deletion on tenant deletion

---

CHANGELOG.md
debian/cron.d
integration_tests/suite/base/test_meeting_authorization.py
integration_tests/suite/helpers/base.py
integration_tests/suite/helpers/database.py
setup.py
wazo_confd/plugins/meeting_authorization/api.yml
wazo_confd/purge_meetings.py

Depends-On: https://github.com/wazo-platform/xivo-dao/pull/172
Why:
* datetime.utcnow() returns UTC time WITHOUT a timezone
* when comparing the database date with a timestamp without a
timezone, PGSQL does the comparison in the local time zone
* when comparing with both timezones, PGSQL applies the corresponding
offset before comparing

Pull request for WAZO-2750-purge-meeting-authorization

---

wazo_confd/plugins/voicemail/api.yml

- api spec: adds an example for `number` in /voicemails POST
motivated by #253

API spec: add voicemail number example

---

README.md
wazo_confd/plugins/api/api.yml
wazo_confd/plugins/func_key/api.yml
wazo_confd/plugins/user_import/api.yml

doc: use wazo-platform.org instead of wazo.community url

---

integration_tests/suite/base/test_meeting_authorization.py
integration_tests/suite/helpers/helpers/user_me_meeting.py

Depends-On: https://github.com/wazo-platform/xivo-dao/pull/175

Pull request for WAZO-2793-meeting-authorizations-edit-require

---

wazo_confd/plugins/wizard/service.py

Depends-On: https://github.com/wazo-platform/wazo-test-helpers/pull/76
Why:
* In order to give permissions to tenant admins, the root user needs to
have all permissions

wizard: give all permissions to root user

---

integration_tests/suite/wizard/test_wizard.py

why: the name of project now include asset name

fix generated docker-compose project name

---

integration_tests/suite/base/test_status.py

**Description:**
* confd takes much more time to start after it has been shut down and restarted. We need to increase the timeout and give it more chances/tries.

Give confd more time/tries to restart

---

integration_tests/suite/base/test_group_member_user.py
integration_tests/suite/base/test_switchboard_member_user.py
integration_tests/suite/base/test_users.py
wazo_confd/plugins/user/resource.py
wazo_confd/plugins/user/schema.py

Fix the error
`werkzeug.routing.BuildError: Could not build url for endpoint 'groups' with values ['id']. Did you forget to specify values ['uuid']?`

Fix uuid needed for schemas

---

wazo_confd/plugins/user/api.yml

`groups: ["string"]` is not correct.
should be `groups: [{ uuid: "string", id: "string" }]`
same thing for switchboards.

Update swagger doc

---

wazo_confd/plugins/user/plugin.py
wazo_confd/plugins/user/sub_resources/resource.py
wazo_confd/plugins/user/sub_resources/schema.py
wazo_confd/plugins/user/tests/test_notifier.py

Put sub-resources classes and schemas in dedicated package. 
This is most consistent with the way schemas and resources are stored in the other plugins: 
- one file for resources definitions (resource.py)
- one file for schemas definitions (schema.py)

Revamp user sub-resources

---

integration_tests/suite/base/test_devices.py
wazo_confd/plugins/device/model.py

Why: this would make it impossible to list the devices

devices: do not raise exception on missing configuration key

---

integration_tests/test-requirements.txt

sqlalchemy version 2.0 needs work before the migration
https://docs.sqlalchemy.org/en/14/changelog/migration_20.html

Limit sqlalchemy to version 1 in tests

---

wazo_confd/plugins/event_handlers/service.py

`notify_early_inuse_ringing` is available to mimick the chan_sip
behaviour for BLF function keys to pickup a call of a user that is
already busy.

[WP-624] event_handlers: add new default endpoint option

---

integration_tests/suite/base/test_sync_db.py
integration_tests/suite/base/test_tenants.py
integration_tests/suite/helpers/base.py
integration_tests/suite/helpers/config.py
wazo_confd/plugins/event_handlers/plugin.py
wazo_confd/sync_db.py

Deletion is triggered by the auth_tenant_deleted event and by cron (synd_db.py)
Depends-On: https://github.com/wazo-platform/xivo-dao/pull/225
Depends-On: https://github.com/wazo-platform/xivo-dao/pull/226
Depends-On: https://github.com/wazo-platform/xivo-dao/pull/227

Improve tenant deletion (including some related resources)

---

integration_tests/suite/base/test_call_permissions.py
integration_tests/suite/base/test_incalls.py

**Why:**
With introduction of query option in DAO, these tests allow to test that query options are being applied to API routes

add db request count test for incalls and callpermissions

---

integration_tests/suite/base/test_pagings.py

Why:
* the test creates 2 different paging, one with a random number, another
with number 123
* when the random number is 123, the test fails

pagings: fix flaky test

---

wazo_confd/plugins/event_handlers/plugin.py
wazo_confd/sync_db.py

When the tenant deletion is called from the CLI (syncdb) the Flask app is not running. So the sysconfd client must be initialized without using a Flask app.

Remove Flask app context from syncdb

---

wazo_confd/config.py
wazo_confd/plugins/meeting/plugin.py
wazo_confd/plugins/user/plugin.py
wazo_confd/plugins/user/service.py
wazo_confd/plugins/user_import/plugin.py

If using large pages (101) or unpaginated queries the existing loading strategy is used. Paginated queries will use the default sqlalchemy behavior, which is lazyloading.
For a small enough number of resource (101 here) this is enough to make the route significantly faster.
Depends-On: https://github.com/wazo-platform/xivo-dao/pull/249

user: select query strategy based on pagination

---

wazo_confd/plugins/provisioning_networking/api.yml
wazo_confd/plugins/registrar/api.yml

why: this key is used for action_uri_limit_ip and must be IPv4.
Otherwise a popup can show up on the device
why: now provision_host is only used for DHCP integration

Pull request for WAZO-3502-simplify-provd-config

---

integration_tests/suite/base/test_func_keys.py
integration_tests/suite/base/test_users_func_keys.py
wazo_confd/plugins/device/generators.py
wazo_confd/plugins/features/resource.py
wazo_confd/plugins/func_key/resource.py
wazo_confd/plugins/func_key/schema.py
wazo_confd/plugins/func_key/tests/test_validator.py
wazo_confd/plugins/func_key/validator.py

Depends-On: https://github.com/wazo-platform/xivo-dao/pull/259
Why:
* the DAO does not need it anymore, since the options are removed from
the database. Those options are now only needed for API validation.
Why:
* They will be reinstated after the funckeys can use parking lots
instead of the global parking

Pull request for WAZO-1870-remove-global-parking

---

wazo_confd/plugins/registrar/service.py

Why: it should not be there at all and it affects HA disabling

registrar: delete sccp backup config when IP is null

---

integration_tests/suite/base/test_sounds.py
wazo_confd/plugins/sound/service.py

Fix sounds' pagination result to be like other resources. `total` is always the `total` of items for the given tenant, when using `limit`, we expect `items` to be limited.
- Create 10 sounds on a tenant
- `GET /sounds?limit=2`
- Expect `items` to have 2 items and `total` to be 10

[WAZO-3695] Sounds - calculate total before filtering

---

integration_tests/suite/base/test_sounds.py

- Stabilize tests, random `name` cause flakiness because of sorting

[WAZO-3695] stabilize test_list with forced names

---

wazo_confd/plugins/event_handlers/service.py

in order to limit maximum call duration using `TIMEOUT(absolute)`

default sip template: added 'set_var' option to default global sip template

---

integration_tests/suite/base/test_ingress_http.py
wazo_confd/helpers/restful.py
wazo_confd/plugins/ingress_http/api.yml
wazo_confd/plugins/ingress_http/resource.py
wazo_confd/plugins/ingress_http/schema.py

- added a new fallback query parameter to be able to retrieve a valid ingress from the master tenant if there's no ingress configured on the current tenant

plugins.ingress_http Allow fallback to master tenant when empty

---

integration_tests/suite/base/test_users.py
integration_tests/suite/helpers/scenarios.py
integration_tests/suite/helpers/wrappers.py

Depends-On: https://github.com/wazo-platform/wazo-test-helpers/pull/108
Why:
* Avoid one failing tests cause failures on subsequent tests

WAZO-3859 Pull request for user-restore-count-db-requests

---

integration_tests/suite/base/test_phone_numbers.py
integration_tests/suite/helpers/fixtures.py
integration_tests/suite/helpers/helpers/phone_number.py
wazo_confd/plugins/phone_number/api.yml
wazo_confd/plugins/phone_number/resource.py
wazo_confd/plugins/phone_number/schema.py
wazo_confd/plugins/phone_number/service.py
wazo_confd/plugins/phone_number/tests/test_service.py
wazo_confd/plugins/phone_number/utils.py

Depends-On: https://github.com/wazo-platform/xivo-dao/pull/288
- off-by-one error in range size validation
- missing '+' prefix in generated range numbers
- multi-tenant support
- missing ACL

phone numbers ranges API fixes

---

wazo_confd/plugins/wizard/service.py
wazo_confd/plugins/wizard/tests/test_service.py

wizard.service: Changed NAMESERVER_REGEX

---

CHANGELOG.md
integration_tests/suite/base/test_queues.py
wazo_confd/plugins/event_handlers/service.py
wazo_confd/plugins/queue/schema.py

Depends-On: https://github.com/wazo-platform/xivo-dao/pull/293
Depends-On: https://github.com/wazo-platform/xivo-manage-db/pull/293

queues: add dtmf_record_toggle

---

wazo_confd/plugins/func_key/api.yml

to GET /funckeys/templates API reference

func_key:api.yml: added missing parameters

---

wazo_confd/plugins/localization/schema.py

Why: The field is not in the event payload otherwise
WAZO-4095

localization: remove tenant_uuid dump only attr

---

etc/nginx/locations/https-available/wazo-confd
etc/nginx/wazo-confd-shared.conf
wazo_confd/plugins/line_endpoint/notifier.py
wazo_confd/plugins/line_endpoint/service.py
wazo_confd/plugins/user_import/auth_client.py

why: it was 15 min before (comment was wrong), but 30min is useful when
having a big import (>2000 users)
All requests to wazo-auth and wazo-provd slowdown import process ...
why: the edit() method is used to call LineFixes helpers.
Using service directly only add an unused layer of validator and send
useless message on bus
The biggest impact is when importing users, the validator will query
wazo-provd for each association, which is ressource consuming
Depends-on: https://github.com/wazo-platform/xivo-dao/pull/303

Pull request for WAZO-4113-users-import-performance

---

integration_tests/Makefile
wazo_confd/database/user_export.py

why: initially in xivo-dao, but was removed to use more optimized query.
However, user export still need to have this sub query. To avoid to be
used by error in another workflow, we scope it here instead of xivo-dao
why: otherwise xivo-dao will be cached and won't be updated

Pull request for fix-user-export

---

integration_tests/suite/base/test_tenants.py

Depends-On: https://github.com/wazo-platform/xivo-dao/pull/309
Depends-On: https://github.com/wazo-platform/xivo-manage-db/pull/303

[WAZO-3523] tenants: add function key destinations to deletion tests

---

integration_tests/suite/helpers/auth.py

why: auth-mock has been updated to expose "_reset" and "_requests"
without version (i.e. without /0.1/_reset)

fix-auth-mock

---

integration_tests/suite/base/test_users.py
wazo_confd/plugins/user/api.yml
wazo_confd/plugins/user/schema.py

depends-on: https://github.com/wazo-platform/xivo-dao/pull/311
- Consume/expose `subscription_type` in view summary

[WAZO-4184]  expose subscription_type in view `summary`

---

integration_tests/suite/base/test_conference_extension.py
integration_tests/suite/base/test_conferences.py
integration_tests/suite/base/test_extensions.py
integration_tests/suite/base/test_group_extension.py
integration_tests/suite/base/test_groups.py
integration_tests/suite/base/test_line_extension.py
integration_tests/suite/base/test_queue_extension.py
integration_tests/suite/base/test_queues.py
integration_tests/suite/base/test_tenants.py
integration_tests/suite/base/test_users.py
integration_tests/suite/helpers/config.py
integration_tests/suite/helpers/helpers/extension.py
integration_tests/suite/helpers/helpers/voicemail.py

why: to remove flaky test when an extension already exists

fix-flaky-tests

---

wazo_confd/plugins/event_handlers/service.py

to force use of sip session timers and detect dead sip peers

sip_templates: change webrtc defaults
