- wazo_confd/plugins/conference/api.yml
conference: fix typo in openapi
conference: add incall relation to openapi
> Pull request for openapi-conference-extension

- wazo_confd/plugins/application/notifier.py
- wazo_confd/plugins/application/tests/test_notifier.py
- wazo_confd/plugins/moh/notifier.py
moh: add body to events
application: add body to events
> Pull request for WAZO-907-cache-application

- CHANGELOG.md
- integration_tests/suite/base/test_line_application.py
- integration_tests/suite/helpers/associations.py
- integration_tests/suite/helpers/helpers/__init__.py
- integration_tests/suite/helpers/helpers/line_application.py
- setup.py
- wazo_confd/config.py
- wazo_confd/plugins/application/api.yml
- wazo_confd/plugins/application/schema.py
- wazo_confd/plugins/line/api.yml
- wazo_confd/plugins/line/schema.py
- wazo_confd/plugins/line_application/api.yml
- wazo_confd/plugins/line_application/notifier.py
- wazo_confd/plugins/line_application/plugin.py
- wazo_confd/plugins/line_application/resource.py
- wazo_confd/plugins/line_application/service.py
- wazo_confd/plugins/line_application/tests/test_notifier.py
- wazo_confd/plugins/line_application/validator.py
line_application: add a warning for the association
add application/line relations
add line_application plugin
> Pull request for WAZO-891-line-application

- wazo_confd/plugins/call_permission/api.yml
- wazo_confd/plugins/outcall/api.yml
- wazo_confd/plugins/outcall/schema.py
- wazo_confd/plugins/trunk/api.yml
outcalls: add tenant_uuid in relations
outcalls: add missing openapi doc
> Pull request for WAZO-938-outcall-relation-doc

- Dockerfile
- debian/wazo-confd.postinst
- debian/wazo-confd.service
- etc/wazo-confd/config.yml
- integration_tests/assets/etc/wazo-confd/conf.d/config.yml
- wazo_confd/config.py
since buster /var/run is a now a symlink to /run
> use /run instead of /var/run

- integration_tests/suite/base/test_func_keys.py
- integration_tests/suite/base/test_user_export.py
- integration_tests/suite/base/test_user_import.py
- wazo_confd/helpers/tests/test_validator.py
- wazo_confd/plugins/func_key/tests/test_notifier.py
- wazo_confd/plugins/func_key/tests/test_validator.py
- wazo_confd/plugins/user/tests/test_validator.py
- wazo_confd/plugins/voicemail/tests/test_validator.py
Fix the coding style such that other PR can be rebased and succeed the linters check
> fix coding style

- wazo_confd/plugins/endpoint_sip/schema.py
Correct regex for implement specific username / provider 
Tested on production
> WAZO-1106: add + in regex

- integration_tests/suite/base/test_trunk_endpoint_custom.py
- integration_tests/suite/base/test_trunk_endpoint_iax.py
- integration_tests/suite/base/test_trunk_endpoint_sip.py
- wazo_confd/plugins/endpoint_custom/notifier.py
- wazo_confd/plugins/endpoint_custom/tests/test_notifier.py
- wazo_confd/plugins/endpoint_iax/notifier.py
- wazo_confd/plugins/endpoint_iax/tests/test_notifier.py
- wazo_confd/plugins/endpoint_sccp/notifier.py
- wazo_confd/plugins/endpoint_sccp/resource.py
- wazo_confd/plugins/endpoint_sccp/schema.py
- wazo_confd/plugins/endpoint_sccp/tests/test_notifier.py
- wazo_confd/plugins/endpoint_sip/notifier.py
- wazo_confd/plugins/endpoint_sip/tests/test_notifier.py
- wazo_confd/plugins/trunk/resource.py
- wazo_confd/plugins/trunk/schema.py
- wazo_confd/plugins/trunk_endpoint/notifier.py
- wazo_confd/plugins/trunk_endpoint/tests/test_notifier.py
trunk_endpoint: add resource infos in events
extract trunk schema on its own module
Depends-on: https://github.com/wazo-platform/xivo-bus/pull/12
> Pull request for WAZO-1330-trunk-status

- integration_tests/suite/base/test_line_endpoint_custom.py
- integration_tests/suite/base/test_line_endpoint_sccp.py
- integration_tests/suite/base/test_line_endpoint_sip.py
- wazo_confd/plugins/line/notifier.py
- wazo_confd/plugins/line/tests/test_notifier.py
- wazo_confd/plugins/line_endpoint/notifier.py
- wazo_confd/plugins/line_endpoint/service.py
Depends-On: https://github.com/wazo-platform/xivo-bus/pull/14
This PR can be merged independently from the calld part of this feature so I'm adding the mergeit tag on bus and confd now in case someone would like to review those parts first.
> line endpoints: publish events on association and dissociation

- integration_tests/suite/base/test_users_func_keys.py
- wazo_confd/plugins/user/service.py
users: update devices for users affected by delete
users: test func_key device update when deleting user
Depends-On: https://github.com/wazo-platform/xivo-dao/pull/28
Depends-On: https://github.com/wazo-platform/xivo-test-helpers/pull/24
> Pull request for WAZO-1197-update-device-deleting-user-funckey

- integration_tests/suite/base/test_lines.py
- wazo_confd/plugins/user/schema.py
Depends-on: https://github.com/wazo-platform/xivo-dao/pull/29
> user: do not execute pre_dump for field that are not required

- integration_tests/suite/base/test_ha.py
- wazo_confd/plugins/ha/plugin.py
- wazo_confd/plugins/ha/service.py
- wazo_confd/plugins/registrar/service.py
registrars: do not return 404 if a device is not found
HA: update SIP and provisioning config
> Pull request for WAZO-1452-ha-update-sip-provisioning

- wazo_confd/plugins/ha/service.py
reason: provd is not running on the slave.
> HA: do not update provisioning when disabling slave

- debian/control
- requirements.txt
werkzeug is used in http_server.py
> explictly add the werkzeug dependency

- CHANGELOG.md
- integration_tests/suite/base/test_groups.py
- integration_tests/suite/base/test_queues.py
- wazo_confd/plugins/group/api.yml
- wazo_confd/plugins/group/schema.py
- wazo_confd/plugins/queue/api.yml
- wazo_confd/plugins/queue/schema.py
Depends-On: https://github.com/wazo-platform/xivo-dao/pull/35
Depends-On: https://github.com/wazo-platform/xivo-manage-db/pull/33
> Add mark_answered_elsewhere on groups and queues

- CHANGELOG.md
- integration_tests/suite/base/test_pjsip_system.py
- wazo_confd/plugins/pjsip/api.yml
- wazo_confd/plugins/pjsip/notifier.py
- wazo_confd/plugins/pjsip/plugin.py
- wazo_confd/plugins/pjsip/resource.py
- wazo_confd/plugins/pjsip/service.py
Depends-On: https://github.com/wazo-platform/xivo-bus/pull/16
Depends-On: https://github.com/wazo-platform/xivo-manage-db/pull/35
> Wazo 1612 add the /asterisk/pjsip/system resource

- integration_tests/suite/base/test_user_import.py
- wazo_confd/plugins/user_import/creators.py
- wazo_confd/plugins/user_import/csvparse.py
reason: otherwise the extension and user are created but not associated
which is useless
> user-import: enforce line_protocol when extension

- wazo_confd/plugins/user/notifier.py
- wazo_confd/plugins/user/tests/test_notifier.py
Depends-On: https://github.com/wazo-platform/xivo-bus/pull/18
> Add id to user Service and Forward events

- CHANGELOG.md
- integration_tests/suite/base/test_pjsip_transports.py
- integration_tests/suite/helpers/fixtures.py
- integration_tests/suite/helpers/helpers/__init__.py
- integration_tests/suite/helpers/helpers/transport.py
- wazo_confd/helpers/validator.py
- wazo_confd/plugins/pjsip/api.yml
- wazo_confd/plugins/pjsip/notifier.py
- wazo_confd/plugins/pjsip/plugin.py
- wazo_confd/plugins/pjsip/resource.py
- wazo_confd/plugins/pjsip/schema.py
- wazo_confd/plugins/pjsip/service.py
- wazo_confd/plugins/pjsip/tests/test_schemas.py
- wazo_confd/plugins/pjsip/validator.py
Depends-On: https://github.com/wazo-platform/xivo-dao/pull/37
Depends-On: https://github.com/wazo-platform/xivo-bus/pull/17
> WAZO-1613 API: add the sip.transport CRUD

- CHANGELOG.md
- integration_tests/suite/base/test_incalls.py
- wazo_confd/plugins/incall/schema.py
Depends-on: https://github.com/wazo-platform/xivo-manage-db/pull/38
Depends-on: https://github.com/wazo-platform/xivo-dao/pull/43
Jira-Issue: https://wazo-dev.atlassian.net/browse/WAZO-1738
> incall: add greeting_sound configuration

- etc/nginx/locations/https-available/wazo-confd
A nicer solution would be to do import async
> increase nginx timeout for big import

- integration_tests/suite/helpers/database.py
- wazo_confd/database/device.py
- wazo_confd/database/user_export.py
- wazo_confd/plugins/device/update.py
- wazo_confd/plugins/device/validator.py
- wazo_confd/plugins/line_device/notifier.py
- wazo_confd/plugins/line_device/service.py
- wazo_confd/plugins/line_device/tests/test_notifier.py
- wazo_confd/plugins/line_device/validator.py
- wazo_confd/plugins/line_endpoint/validator.py
- wazo_confd/plugins/trunk_endpoint/validator.py
- wazo_confd/plugins/user_import/entry.py
Depends-on: https://github.com/wazo-platform/xivo-manage-db/pull/41
Depends-on: https://github.com/wazo-platform/xivo-dao/pull/44
Jira-Issue: https://wazo-dev.atlassian.net/browse/WAZO-1771
> linefeatures: use endpoint_sccp_id instead protocolid

- wazo_confd/plugins/line_endpoint/validator.py
- wazo_confd/plugins/trunk/notifier.py
- wazo_confd/plugins/trunk/tests/test_notifier.py
- wazo_confd/plugins/trunk_endpoint/validator.py
Depends-on: https://github.com/wazo-platform/xivo-dao/pull/45
Depends-on: https://github.com/wazo-platform/xivo-manage-db/pull/43
> use endpoint_*_id/register_*_id trunk columns

- etc/wazo-confd/config.yml
- wazo_confd/config.py
reason: consul is configured to http
> remove irrelevant verify consul option

- Dockerfile
- integration_tests/suite/base/test_endpoint_sip.py
- integration_tests/suite/base/test_pjsip_transports.py
- integration_tests/suite/helpers/associations.py
- integration_tests/suite/helpers/client.py
- integration_tests/suite/helpers/helpers/__init__.py
- integration_tests/suite/helpers/helpers/transport.py
- integration_tests/suite/helpers/helpers/transport_endpoint_sip.py
- wazo_confd/helpers/mallow.py
- wazo_confd/plugins/endpoint_sip/plugin.py
- wazo_confd/plugins/endpoint_sip/resource.py
- wazo_confd/plugins/pjsip/resource.py
- wazo_confd/plugins/pjsip/schema.py
- wazo_confd/plugins/pjsip/service.py
- wazo_confd/plugins/pjsip/validator.py
Depends-on: https://github.com/wazo-platform/xivo-dao/pull/49
> Pull request for transport-delete-fallback

- integration_tests/suite/base/test_line_endpoint_sip.py
- wazo_confd/plugins/line_endpoint/notifier.py
- wazo_confd/plugins/line_endpoint/plugin.py
- wazo_confd/plugins/line_endpoint/service.py
- wazo_confd/plugins/line_endpoint/validator.py
- wazo_confd/plugins/trunk_endpoint/notifier.py
- wazo_confd/plugins/trunk_endpoint/plugin.py
- wazo_confd/plugins/trunk_endpoint/service.py
- wazo_confd/plugins/trunk_endpoint/tests/test_notifier.py
- wazo_confd/plugins/trunk_endpoint/validator.py
- wazo_confd/plugins/user_import/associators.py
- wazo_confd/plugins/user_import/plugin.py
Depends-on: https://github.com/wazo-platform/xivo-dao/pull/46
> Pull request for WAZO-1776-refactor-association-endpoint

- integration_tests/suite/helpers/database.py
Depends-on: https://github.com/wazo-platform/xivo-manage-db/pull/51
> test: remove numgroup column on agent table

- wazo_confd/plugins/endpoint_sip/api.yml
- templatess => templates
- Remove template from body request
> PJSIP - Api spec typos

- CHANGELOG.md
- integration_tests/suite/base/test_func_keys.py
- integration_tests/suite/base/test_func_keys_templates.py
- integration_tests/suite/helpers/helpers/funckey_template.py
- wazo_confd/plugins/func_key/api.yml
- wazo_confd/plugins/func_key/resource.py
- wazo_confd/plugins/func_key/schema.py
- wazo_confd/plugins/func_key/service.py
- wazo_confd/plugins/func_key/tests/test_service.py
- wazo_confd/plugins/func_key/tests/test_validator.py
- wazo_confd/plugins/func_key/validator.py
Depends-on: https://github.com/wazo-platform/xivo-dao/pull/58
Depends-on: https://github.com/wazo-platform/xivo-manage-db/pull/55
> Pull request for WAZO-1834-func-key-template-multi-tenant

- Dockerfile
- debian/wazo-confd.postinst
- debian/wazo-confd.service
- etc/wazo-confd/config.yml
- wazo_confd/config.py
- wazo_confd/main.py
reason: systemd restart remove monit usage based on pid file
> Pull request for WAZO-1842-remove-pid

- etc/wazo-confd/config.yml
- integration_tests/suite/base/test_event_handlers.py
- integration_tests/suite/base/test_sync_db.py
- integration_tests/suite/helpers/base.py
- integration_tests/suite/helpers/bus.py
- integration_tests/suite/helpers/config.py
- integration_tests/suite/helpers/database.py
- setup.py
- wazo_confd/_bus.py
- wazo_confd/config.py
- wazo_confd/controller.py
- wazo_confd/helpers/restful.py
- wazo_confd/http_server.py
- wazo_confd/plugins/endpoint_sip/api.yml
- wazo_confd/plugins/endpoint_sip/schema.py
- wazo_confd/plugins/event_handlers/plugin.py
- wazo_confd/plugins/event_handlers/service.py
- wazo_confd/plugins/user_import/service.py
- wazo_confd/sync_db.py
Depends-on: https://github.com/wazo-platform/xivo-manage-db/pull/58
Depends-on: https://github.com/wazo-platform/xivo-dao/pull/61
> Wazo 1874 default template

- integration_tests/suite/base/test_endpoint_sip.py
- integration_tests/suite/base/test_user_line_associated.py
- integration_tests/suite/helpers/associations.py
- integration_tests/suite/helpers/helpers/__init__.py
- integration_tests/suite/helpers/helpers/endpoint_sip_template_sip.py
- wazo_confd/plugins/endpoint_sip/api.yml
- wazo_confd/plugins/endpoint_sip/resource.py
- wazo_confd/plugins/endpoint_sip/schema.py
- wazo_confd/plugins/endpoint_sip/tests/test_schema.py
- wazo_confd/plugins/trunk_endpoint/tests/test_notifier.py
- wazo_confd/plugins/user_line_associated/api.yml
- wazo_confd/plugins/user_line_associated/resource.py
Depends-on: https://github.com/wazo-platform/xivo-dao/pull/73
> Wazo 1965 merged pjsip options

- integration_tests/suite/base/test_event_handlers.py
- integration_tests/suite/base/test_sync_db.py
- wazo_confd/plugins/event_handlers/service.py
Depends-on: https://github.com/wazo-platform/xivo-manage-db/pull/75
Depends-on: https://github.com/wazo-platform/xivo-dao/pull/75
Test do not seems to pass on my computer, will see with Zuul
> [WAZO-1971] Add default template webrtc_video

- wazo_confd/sync_db.py
reason: the old config affected only the logger in the current file
ex: Executing `wazo-confd-sync-db --quiet` still produce an output
because logger in other files (service.py) was not affected
> sync-db: use xivo_logging to setup logger

- CHANGELOG.md
- integration_tests/suite/base/test_tenants.py
- setup.py
- wazo_confd/config.py
- wazo_confd/plugins/tenant/api.yml
- wazo_confd/plugins/tenant/plugin.py
- wazo_confd/plugins/tenant/resource.py
- wazo_confd/plugins/tenant/schema.py
- wazo_confd/plugins/tenant/service.py
add GET /tenants and GET /tenants/<uuid>
Depends-On: https://github.com/wazo-platform/xivo-dao/pull/83
> tenants: add methods to get tenants

- CHANGELOG.md
- integration_tests/suite/base/test_external_apps.py
- integration_tests/suite/helpers/fixtures.py
- integration_tests/suite/helpers/helpers/__init__.py
- integration_tests/suite/helpers/helpers/external_app.py
- setup.py
- wazo_confd/config.py
- wazo_confd/plugins/external_app/api.yml
- wazo_confd/plugins/external_app/notifier.py
- wazo_confd/plugins/external_app/plugin.py
- wazo_confd/plugins/external_app/resource.py
- wazo_confd/plugins/external_app/schema.py
- wazo_confd/plugins/external_app/service.py
- wazo_confd/plugins/external_app/tests/test_notifier.py
- wazo_confd/plugins/external_app/validator.py
- wazo_confd/plugins/incall/validator.py
Depends-on: https://github.com/wazo-platform/xivo-bus/pull/28
Depends-on: https://github.com/wazo-platform/xivo-dao/pull/90
Depends-on: https://github.com/wazo-platform/xivo-manage-db/pull/88
> Pull request for WAZO-2041-external-app-tenant

- CHANGELOG.md
- integration_tests/suite/base/test_user_external_apps.py
- integration_tests/suite/helpers/fixtures.py
- integration_tests/suite/helpers/helpers/__init__.py
- integration_tests/suite/helpers/helpers/user_external_app.py
- integration_tests/suite/helpers/wrappers.py
- setup.py
- wazo_confd/config.py
- wazo_confd/plugins/api/api.yml
- wazo_confd/plugins/external_app/api.yml
- wazo_confd/plugins/user_external_app/api.yml
- wazo_confd/plugins/user_external_app/notifier.py
- wazo_confd/plugins/user_external_app/plugin.py
- wazo_confd/plugins/user_external_app/resource.py
- wazo_confd/plugins/user_external_app/schema.py
- wazo_confd/plugins/user_external_app/service.py
- wazo_confd/plugins/user_external_app/tests/test_notifier.py
- wazo_confd/plugins/user_external_app/validator.py
- wazo_confd/plugins/user_line_associated/api.yml
Depends-on: https://github.com/wazo-platform/xivo-manage-db/pull/91
Depends-on: https://github.com/wazo-platform/xivo-bus/pull/29
Depends-on: https://github.com/wazo-platform/xivo-dao/pull/92
> Pull request for WAZO-2042-external-app-user

- integration_tests/suite/base/test_user_import.py
- wazo_confd/plugins/user_import/creators.py
at the moment sip endpoint for lines need to have a matching name and username
to work properly
> user import: set the name to the username

- wazo_confd/_bus.py
Depends-On: https://github.com/wazo-platform/xivo-bus/pull/30
> bus: use correct policy for publishing

- integration_tests/suite/base/test_user_import.py
- wazo_confd/plugins/user_import/creators.py
- wazo_confd/plugins/user_import/plugin.py
Depends-on: https://github.com/wazo-platform/xivo-dao/pull/99/
> import csv: add SIP templates

- integration_tests/suite/base/test_features_applicationmap.py
- integration_tests/suite/base/test_features_featuremap.py
- wazo_confd/plugins/features/resource.py
Depends-On: https://github.com/wazo-platform/xivo-dao/pull/101
Depends-On: https://github.com/wazo-platform/xivo-manage-db/pull/98
Depends-On: https://github.com/wazo-platform/xivo-manage-db/pull/99/files
> WAZO-2059-refactor-online-call-record

- CHANGELOG.md
- integration_tests/suite/base/test_emails.py
- setup.py
- tox.ini
- wazo_confd/config.py
- wazo_confd/database/email.py
- wazo_confd/plugins/email/api.yml
- wazo_confd/plugins/email/notifier.py
- wazo_confd/plugins/email/plugin.py
- wazo_confd/plugins/email/resource.py
- wazo_confd/plugins/email/schema.py
- wazo_confd/plugins/email/service.py
- wazo_confd/plugins/email/tests/test_notifier.py
- wazo_confd/plugins/email/tests/test_schema.py
Depends-On: https://github.com/wazo-platform/xivo-bus/pull/33
Depends-On: https://github.com/wazo-platform/wazo-confd-client/pull/25
Relates-To: https://github.com/wazo-platform/wazo-auth/pull/136
> Pull request for WAZO-2292-email-config

- etc/wazo-confd/config.yml
Relates-To: https://github.com/wazo-platform/xivo-sysconfd/pull/24
> WAZO-1552: rename xivo-sysconfd to wazo-sysconfd

- CHANGELOG.md
- integration_tests/suite/base/test_switchboards.py
- wazo_confd/plugins/switchboard/api.yml
- wazo_confd/plugins/switchboard/plugin.py
- wazo_confd/plugins/switchboard/resource.py
Depends-On: https://github.com/wazo-platform/xivo-dao/pull/123
Depends-On: https://github.com/wazo-platform/xivo-manage-db/pull/119
> switchboard: add moh fields

- integration_tests/Makefile
- integration_tests/suite/base/test_switchboard_fallback.py
- integration_tests/suite/base/test_switchboards.py
- setup.py
- wazo_confd/config.py
- wazo_confd/plugins/switchboard/schema.py
- wazo_confd/plugins/switchboard_fallback/api.yml
- wazo_confd/plugins/switchboard_fallback/notifier.py
- wazo_confd/plugins/switchboard_fallback/plugin.py
- wazo_confd/plugins/switchboard_fallback/resource.py
- wazo_confd/plugins/switchboard_fallback/schema.py
- wazo_confd/plugins/switchboard_fallback/service.py
- wazo_confd/plugins/switchboard_fallback/tests/test_notifier.py
- wazo_confd/plugins/switchboard_fallback/validator.py
Depends-On: https://github.com/wazo-platform/xivo-dao/pull/125
Depends-On: https://github.com/wazo-platform/xivo-manage-db/pull/121
Depends-On: https://github.com/wazo-platform/xivo-bus/pull/41
> Pull request for WAZO-2422-switchboard-fallback-noanswer

- CHANGELOG.md
- integration_tests/suite/base/test_call_filter_surrogate_user.py
- wazo_confd/plugins/call_filter/api.yml
- wazo_confd/plugins/call_filter/schema.py
Depends-On: https://github.com/wazo-platform/xivo-dao/pull/138
> WAZO-2488 Add exten to callfilter surrogate users

- wazo_confd/plugins/meeting/resource.py
Depends-On: https://github.com/wazo-platform/xivo-lib-python/pull/86
> refactor: use the user_uuid from the request

- CHANGELOG.md
- integration_tests/suite/base/test_meeting.py
- wazo_confd/plugins/meeting/api.yml
- wazo_confd/plugins/meeting/schema.py
- wazo_confd/purge_meetings.py
Depends-On: https://github.com/wazo-platform/xivo-dao/pull/150
Depends-On: https://github.com/wazo-platform/xivo-manage-db/pull/144
> Wazo 2613 persistent meetings

- integration_tests/suite/base/test_auth.py
- integration_tests/suite/helpers/auth.py
- integration_tests/test-requirements.txt
why: to have the latest docker-compose
> use docker-compose from binary instead of python

- wazo_confd/plugins/queue_member/notifier.py
- wazo_confd/plugins/queue_member/tests/test_notifier.py
Why:
* Previous implementation used sysconfd to send the EditAgentEvent.  That system is deprecated and we now send the event directly from confd
> WAZO-2710: Send EditAgentEvent bus message directly from confd

- integration_tests/suite/base/test_meeting.py
> Pull request for WAZO-2768-meeting-ingress-tests

- CHANGELOG.md
- integration_tests/suite/base/test_user_subscription.py
- setup.py
- wazo_confd/config.py
- wazo_confd/plugins/user_subscription/api.yml
- wazo_confd/plugins/user_subscription/plugin.py
- wazo_confd/plugins/user_subscription/resource.py
- wazo_confd/plugins/user_subscription/service.py
Depends-on: https://github.com/wazo-platform/xivo-dao/pull/173
> Pull request for WAZO-2790-count-subscription

- integration_tests/suite/base/test_parking_lots.py
- integration_tests/suite/base/test_users.py
Why:
* moh have been removed from searchable fields in dao
> tests: remove tests search on moh

- README.md
- integration_tests/suite/base/test_meeting.py
UTC timezone specified
README updated (python3)
> WP-676 fix integration tests missing utc timezone

- integration_tests/suite/base/test_line_extension.py
- wazo_confd/plugins/extension/api.yml
- wazo_confd/plugins/extension/validator.py
- wazo_confd/plugins/line/api.yml
Depends-On: https://github.com/wazo-platform/xivo-manage-db/pull/170
Depends-On: https://github.com/wazo-platform/xivo-dao/pull/177
> Wp 665 delete associated extension

- CHANGELOG.md
- integration_tests/suite/base/__init__.py
- integration_tests/suite/base/test_line_endpoint_custom.py
- integration_tests/suite/base/test_line_endpoint_sccp.py
- integration_tests/suite/base/test_line_endpoint_sip.py
- integration_tests/suite/base/test_line_extension.py
- integration_tests/suite/base/test_lines.py
- integration_tests/suite/base/test_user_import.py
- integration_tests/suite/base/test_users.py
- wazo_confd/helpers/restful.py
- wazo_confd/plugins/endpoint_sip/resource.py
- wazo_confd/plugins/endpoint_sip/tests/test_schema.py
- wazo_confd/plugins/extension/resource.py
- wazo_confd/plugins/line/api.yml
- wazo_confd/plugins/line/plugin.py
- wazo_confd/plugins/line/resource.py
- wazo_confd/plugins/line/schema.py
- wazo_confd/plugins/line_extension/resource.py
- wazo_confd/plugins/pjsip/resource.py
- wazo_confd/plugins/user/api.yml
- wazo_confd/plugins/user/plugin.py
- wazo_confd/plugins/user/resource.py
- wazo_confd/plugins/user/schema.py
Reverts wazo-platform/wazo-confd#292
> Revert "Wazo 2864 user api 1.1"

- CHANGELOG.md
- integration_tests/suite/base/test_event_handlers.py
- integration_tests/suite/base/test_sync_db.py
- integration_tests/suite/base/test_tenants.py
- wazo_confd/plugins/event_handlers/service.py
- wazo_confd/plugins/tenant/api.yml
- wazo_confd/plugins/tenant/schema.py
Depends-On: https://github.com/wazo-platform/xivo-dao/pull/183
> tenants: merge webrtc_video sip template into webrtc

- integration_tests/suite/base/test_user_group.py
At the moment only the main line of a user is a queue member (group/queue) deleting a secondary line from a user should not have an impact on the user's group or queue membership.
Depends-On: https://github.com/wazo-platform/xivo-dao/pull/186
> user group: add a test case for multi line scenario

- CHANGELOG.md
- integration_tests/suite/base/test_users.py
- wazo_confd/plugins/endpoint_sip/middleware.py
- wazo_confd/plugins/endpoint_sip/plugin.py
- wazo_confd/plugins/endpoint_sip/resource.py
- wazo_confd/plugins/extension/middleware.py
- wazo_confd/plugins/extension/plugin.py
- wazo_confd/plugins/extension/resource.py
- wazo_confd/plugins/incall/middleware.py
- wazo_confd/plugins/incall/plugin.py
- wazo_confd/plugins/incall/resource.py
- wazo_confd/plugins/line/middleware.py
- wazo_confd/plugins/line/plugin.py
- wazo_confd/plugins/line/resource.py
- wazo_confd/plugins/line_extension/middleware.py
- wazo_confd/plugins/user/api.yml
- wazo_confd/plugins/user/middleware.py
- wazo_confd/plugins/user/resource.py
- wazo_confd/plugins/user_import/auth_client.py
- wazo_confd/plugins/user_import/wazo_user_service.py
- wazo_confd/plugins/user_line/middleware.py
- delete the user and their resources
- cleanup tests
> Recursive deletion for a user

- integration_tests/suite/base/test_users.py
- wazo_confd/plugins/user/middleware.py
- wazo_confd/plugins/user/sub_resources/middleware.py
- wazo_confd/plugins/user_voicemail/middleware.py
- wazo_confd/plugins/user_voicemail/resource.py
waiting https://github.com/wazo-platform/wazo-confd/pull/335 before
> Add fallback/forward support

- integration_tests/suite/base/test_users.py
- wazo_confd/plugins/user/middleware.py
Fix error:
`500 ["Unexpected error: 'UserFeatures' object has no attribute 'user'"]`
> Fix issue with switchboard uuid on user creation

- integration_tests/suite/base/test_users.py
- wazo_confd/plugins/device/middleware.py
- wazo_confd/plugins/device/plugin.py
- wazo_confd/plugins/device/resource.py
- wazo_confd/plugins/user/middleware.py
- `FormattedError` is not used as it should be
- Enhance device middleware
- middleware `unallocated_device_middleware` renamed to `device`
> Fix issue with device on user creation

- debian/wazo-confd.service
- setup.py
- wazo_confd/wait.py
reason: So that systemd knows when the daemon is ready
It make wazo-acceptance-ha test fail
> add wazo-confd-wait command

- wazo_confd/plugins/api/api.yml
depends-on: https://github.com/wazo-platform/wazo-platform.org/pull/613
> [WAZO-3270] Add logo to spec

- integration_tests/assets/mocks/sysconfd.py
- integration_tests/suite/base/__init__.py
- integration_tests/suite/base/test_dhcp.py
- wazo_confd/_sysconfd.py
- wazo_confd/plugins/dhcp/exceptions.py
- wazo_confd/plugins/dhcp/notifier.py
- wazo_confd/plugins/dhcp/plugin.py
- wazo_confd/plugins/dhcp/service.py
- wazo_confd/tests/test_sysconfd.py
https://wazo-dev.atlassian.net/browse/WP-876
Depends-on: https://github.com/wazo-platform/wazo-sysconfd/pull/82
> WP-876 dhcp validation

- integration_tests/test-requirements.txt
depends-on: https://github.com/wazo-platform/wazo-auth-client/pull/39
> Removed duplicated transitive dependency

- integration_tests/suite/base/test_endpoint_sip.py
- integration_tests/suite/base/test_endpoint_sip_templates.py
- integration_tests/suite/base/test_extensions.py
- integration_tests/suite/base/test_lines.py
- integration_tests/suite/base/test_users.py
- integration_tests/suite/helpers/scenarios.py
Depends-On: https://github.com/wazo-platform/xivo-dao/pull/222
> Pull request for WAZO-3288-fix-user-regression

- wazo_confd/plugins/incall/service.py
Depends-On: https://github.com/wazo-platform/xivo-dao/pull/238
> WP-1059: add incalls query options

- CHANGELOG.md
- integration_tests/suite/base/test_call_filter_surrogate_user.py
- integration_tests/suite/base/test_extensions_features.py
- integration_tests/suite/base/test_meeting.py
- integration_tests/suite/helpers/database.py
- integration_tests/suite/helpers/fixtures.py
- integration_tests/suite/helpers/helpers/extension_feature.py
- wazo_confd/plugins/device/builder.py
- wazo_confd/plugins/device/funckey.py
- wazo_confd/plugins/device/generators.py
- wazo_confd/plugins/extension/service.py
- wazo_confd/plugins/extension_feature/api.yml
- wazo_confd/plugins/extension_feature/notifier.py
- wazo_confd/plugins/extension_feature/plugin.py
- wazo_confd/plugins/extension_feature/resource.py
- wazo_confd/plugins/extension_feature/schema.py
- wazo_confd/plugins/extension_feature/service.py
- wazo_confd/plugins/extension_feature/tests/test_notifier.py
- wazo_confd/plugins/extension_feature/validator.py
- wazo_confd/plugins/meeting/notifier.py
- wazo_confd/plugins/meeting/resource.py
Depends-On: https://github.com/wazo-platform/xivo-dao/pull/239
> Use new features extensions

- zuul.yaml
why: to be able to test some specific branch against acceptance
> Pull request for add-experimental-pipeline

- wazo_confd/_sysconfd.py
- wazo_confd/sync_db.py
- wazo_confd/tests/test_sysconfd.py
must be merged after https://github.com/wazo-platform/xivo-manage-db/pull/230
Depends-On: https://github.com/wazo-platform/wazo-sysconfd/pull/90
> Wazo 3405 delete moh

- CHANGELOG.md
- integration_tests/suite/base/test_skills.py
- integration_tests/suite/base/test_tenants.py
- wazo_confd/plugins/skill/api.yml
- wazo_confd/plugins/skill/schema.py
Depends-on: https://github.com/wazo-platform/xivo-dao/pull/248
> Wazo 3350 - Remove queueskill category

- integration_tests/suite/base/test_tenants.py
Depends-On: https://github.com/wazo-platform/xivo-dao/pull/250
Depends-On: https://github.com/wazo-platform/xivo-manage-db/pull/237
> Add func_key_dest_conf in tests when deleting tenant

- integration_tests/suite/base/test_agents.py
- integration_tests/suite/helpers/config.py
- wazo_confd/plugins/agent/service.py
- wazo_confd/plugins/agent/validator.py
Depends-On: https://github.com/wazo-platform/xivo-dao/pull/252
Depends-On: https://github.com/wazo-platform/xivo-manage-db/pull/239
> Add number+tenant_uuid as unique for agentfeatures

- integration_tests/suite/base/test_users.py
Depends-On: https://github.com/wazo-platform/xivo-dao/pull/256
> users: fix sort by id

- integration_tests/suite/base/test_parking_lot_extension.py
- integration_tests/suite/base/test_parking_lots.py
- integration_tests/suite/helpers/errors.py
- integration_tests/suite/helpers/scenarios.py
- wazo_confd/plugins/extension/validator.py
- wazo_confd/plugins/parking_lot/validator.py
- wazo_confd/plugins/parking_lot_extension/validator.py
Depends-On: https://github.com/wazo-platform/xivo-dao/pull/263
> Pull request for WP-1274-parking-range-validation

- integration_tests/suite/base/test_schedules.py
Depends-on: https://github.com/wazo-platform/xivo-dao/pull/268
> Pull request for WAZO-2877-add-relation-to-schedule-destinations

- CHANGELOG.md
- integration_tests/README.md
- integration_tests/suite/base/test_func_keys.py
- integration_tests/suite/base/test_func_keys_destinations.py
- integration_tests/suite/helpers/database.py
- integration_tests/suite/helpers/errors.py
- wazo_confd/plugins/device/funckey.py
- wazo_confd/plugins/func_key/resource.py
- wazo_confd/plugins/func_key/schema.py
- wazo_confd/plugins/func_key/validator.py
Depends-on: https://github.com/wazo-platform/xivo-dao/pull/267
Depends-on: https://github.com/wazo-platform/xivo-manage-db/pull/250
> Pull request for WP-1276-parking-function-keys

- wazo_confd/plugins/meeting/resource.py
- wazo_confd/plugins/meeting_authorization/resource.py
Depends-on: https://github.com/wazo-platform/xivo-lib-python/pull/140
> use flask user object to retrieve user_uuid

- integration_tests/suite/base/test_ingress_http.py
- wazo_confd/plugins/ingress_http/notifier.py
- wazo_confd/plugins/ingress_http/plugin.py
- wazo_confd/plugins/ingress_http/resource.py
- wazo_confd/plugins/ingress_http/schema.py
- wazo_confd/plugins/ingress_http/service.py
- wazo_confd/plugins/ingress_http/validator.py
why: to avoid false negative and let user everything is fine with his
query string when doing a typo
ex: if a user has ingress but use view with a typo (view=fallbak), then
the error will occurs only on the next GET after the day he will remove
his ingress
> Pull request for fix-styling-issue

- debian/wazo-confd.dirs
- debian/wazo-confd.service
- etc/rsyslog.d/99-wazo-confd.conf
> WAZO-3682: disable logs to rsyslog

- integration_tests/suite/base/test_localization.py
- wazo_confd/plugins/localization/notifier.py
Depends-On: https://github.com/wazo-platform/wazo-bus/pull/112
> localization: add tests for bus event

- CHANGELOG.md
- integration_tests/suite/base/test_endpoint_sip.py
- integration_tests/suite/base/test_users.py
- wazo_confd/plugins/api/api.yml
- wazo_confd/plugins/endpoint_sip/api.yml
- wazo_confd/plugins/user/api.yml
Depends-On: https://github.com/wazo-platform/xivo-dao/pull/281
> Wazo 3874 sip endpoint list by UUID

- wazo_confd/http_server.py
> HTTP server: apply cheroot patch

- integration_tests/suite/base/test_phone_numbers.py
- wazo_confd/helpers/common.py
- wazo_confd/helpers/types.py
- wazo_confd/plugins/api/api.yml
- wazo_confd/plugins/phone_number/api.yml
- wazo_confd/plugins/phone_number/plugin.py
- wazo_confd/plugins/phone_number/resource.py
- wazo_confd/plugins/phone_number/schema.py
- wazo_confd/plugins/phone_number/service.py
- wazo_confd/plugins/phone_number/tests/test_service.py
- wazo_confd/plugins/phone_number/tests/test_utils.py
- wazo_confd/plugins/phone_number/utils.py
Depends-On:https://github.com/wazo-platform/xivo-dao/pull/284
- **plugins.phone_number: added utils module**
- **plugins.phone_number.schema: number_field marshmallow utility**
- **plugins.phone_number.schema: schemas for range API**
- **plugins.phone_number.tests: test coverage for utils**
- **plugins.api: added definition for Link object in openapi spec**
- **plugins.phone_number: updated api.yml with range API info**
- **fixup: 72eecd3aceaece1e66817d349fd304c70e1f6483 schemas**
- **fixup: 72eecd3aceaece1e66817d349fd304c70e1f6483 schema(links)**
- **plugins.phone_number.service: added a custom PhoneNumberService with create_range method**
- **helpers.common: updated api exception handler**
- **plugins.phone_number.resource: range resource endpoint**
- **plugins.phone_number.plugin: …
> WAZO 3922 bulk phone numbers api

- CHANGELOG.md
- integration_tests/suite/base/test_group_fallback.py
- integration_tests/suite/base/test_groups.py
- wazo_confd/plugins/group/api.yml
- wazo_confd/plugins/group/schema.py
- wazo_confd/plugins/group_fallback/api.yml
- wazo_confd/plugins/group_fallback/schema.py
Depends-On: https://github.com/wazo-platform/xivo-dao/pull/283
> [WP-1574] ring group max calls

- CHANGELOG.md
- integration_tests/suite/base/test_trunks.py
- wazo_confd/plugins/trunk/api.yml
- wazo_confd/plugins/trunk/schema.py
Depends-On: https://github.com/wazo-platform/xivo-dao/pull/285
Depends-On: https://github.com/wazo-platform/xivo-manage-db/pull/277
> WAZO-3944-outgoing-caller-id-format

- integration_tests/suite/base/test_phone_numbers.py
- wazo_confd/plugins/phone_number/api.yml
- wazo_confd/plugins/phone_number/notifier.py
- wazo_confd/plugins/phone_number/plugin.py
- wazo_confd/plugins/phone_number/resource.py
- wazo_confd/plugins/phone_number/schema.py
- wazo_confd/plugins/phone_number/service.py
- wazo_confd/plugins/phone_number/tests/test_service.py
- wazo_confd/plugins/phone_number/utils.py
Depends-On: https://github.com/wazo-platform/wazo-bus/pull/116
> phone_numbers: updated api.yml PhoneNumber definition

- integration_tests/suite/base/test_phone_numbers.py
- integration_tests/suite/helpers/helpers/phone_number.py
- wazo_confd/plugins/phone_number/schema.py
- **phone_number: updated PhoneNumber schema for read-only 'main'**
- **integration_tests: phone_number: 'main' number handling in fixture**
- **phone_number: test_phone_numbers: refactored tests**
> phone numbers main read only

- integration_tests/suite/base/test_phone_numbers.py
Depends-On: https://github.com/wazo-platform/xivo-dao/pull/289
> phone_numbers: check that setting a number as main also makes it shared

- CHANGELOG.md
- wazo_confd/plugins/user_callerid/api.yml
- **user_callerid: updated api schema**
- **CHANGELOG.md: added entries for 24.16**
> 24.16 missing changelog

- integration_tests/suite/base/test_incalls.py
- wazo_confd/plugins/api/api.yml
- wazo_confd/plugins/incall/api.yml
Actual changes were done in the dao, this is only about documentation.
> WAZO-3423 search incalls by user_id

- integration_tests/suite/helpers/database.py
Depends-On: https://github.com/wazo-platform/xivo-manage-db/pull/288
> refactor: base test db got renamed

- CHANGELOG.md
- integration_tests/suite/base/test_groups.py
- wazo_confd/plugins/group/schema.py
Depends-On: https://github.com/wazo-platform/xivo-dao/pull/295
Depends-On: https://github.com/wazo-platform/xivo-manage-db/pull/295
> Wazo 4029 group record toggle

- integration_tests/suite/base/test_devices.py
- wazo_confd/plugins/device/service.py
Needed for https://github.com/wazo-platform/wazo-agid/pull/182.
Thx 👍
> Narrow autoprov devices discovery

- CHANGELOG.md
- integration_tests/suite/base/test_recordings.py
- setup.py
- wazo_confd/config.py
- wazo_confd/plugins/recordings/api.yml
- wazo_confd/plugins/recordings/notifier.py
- wazo_confd/plugins/recordings/plugin.py
- wazo_confd/plugins/recordings/resource.py
- wazo_confd/plugins/recordings/schema.py
- wazo_confd/plugins/recordings/service.py
Depends-On: https://github.com/wazo-platform/wazo-bus/pull/118
> [WAZO-4032] recordings_annoucements: add plugin

- integration_tests/suite/base/test_localization.py
- wazo_confd/plugins/localization/api.yml
- wazo_confd/plugins/localization/schema.py
Depends-On: https://github.com/wazo-platform/wazo-bus/pull/119
> [WAZO-4095] localization: add tenant_uuid to schema

- wazo_confd/plugins/localization/schema.py
This reverts commit dde227a172757f2a09a8e863b622e0a2cb511d9a.
> Revert "localization: remove tenant_uuid dump only attr"

- integration_tests/suite/base/test_user_blocklist.py
- integration_tests/suite/helpers/fixtures.py
- integration_tests/suite/helpers/helpers/__init__.py
- integration_tests/suite/helpers/helpers/blocklist.py
- integration_tests/test-requirements.txt
- setup.py
- wazo_confd/config.py
- wazo_confd/helpers/mallow.py
- wazo_confd/helpers/restful.py
- wazo_confd/plugins/user_blocklist/api.yml
- wazo_confd/plugins/user_blocklist/notifier.py
- wazo_confd/plugins/user_blocklist/plugin.py
- wazo_confd/plugins/user_blocklist/resource.py
- wazo_confd/plugins/user_blocklist/schema.py
- wazo_confd/plugins/user_blocklist/service.py
- wazo_confd/plugins/user_blocklist/validator.py
Depends-On: https://github.com/wazo-platform/xivo-dao/pull/302
Depends-On: https://github.com/wazo-platform/xivo-manage-db/pull/301
Depends-On: https://github.com/wazo-platform/wazo-bus/pull/121
> user_blocklist: user api CRUD

- integration_tests/suite/base/test_blocklist.py
- integration_tests/suite/helpers/client.py
- integration_tests/suite/helpers/utils.py
- wazo_confd/helpers/mallow.py
- wazo_confd/plugins/phone_number/schema.py
- wazo_confd/plugins/user_blocklist/api.yml
- wazo_confd/plugins/user_blocklist/plugin.py
- wazo_confd/plugins/user_blocklist/resource.py
- wazo_confd/plugins/user_blocklist/schema.py
Depends-On: https://github.com/wazo-platform/xivo-dao/pull/308
> blocklist: admin API

- integration_tests/suite/base/test_blocklist.py
- wazo_confd/plugins/user_blocklist/api.yml
- wazo_confd/plugins/user_blocklist/resource.py
why: consistency, completeness
> blocklist: add GET support for /users/<uuid>/blocklist/numbers

- integration_tests/suite/base/test_blocklist.py
- wazo_confd/plugins/user_blocklist/api.yml
- wazo_confd/plugins/user_blocklist/schema.py
Why:
* Easier to build UI around this API
> blocklist: add user firstname+lastname

- wazo_confd/plugins/group/api.yml
with missing ignore_forward field
> group: updated spec
